CREATE TABLE IF NOT EXISTS split_bot_chat_whitelist (
    id SERIAL PRIMARY KEY,
    group_id VARCHAR NOT NULL UNIQUE,
    platform_type VARCHAR NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP
);
